title: Code With Ganesh
description: Software engineer sharing coding tutorials, tech insights, and development tips
url: "https://ganeshrajugalla.github.io"
baseurl: "/codewithganesh.github.io"

author:
  name: Ganesh Raju Galla
  email: ganeshrajugalla@gmail.com
  twitter: codewithganesh
  github: GaneshRajuGalla

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

theme: minima
